# Generated by Django 5.1.6 on 2025-04-28 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avertisment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avertisment', models.DateTimeField(auto_now_add=True)),
                ('motiv', models.CharField(max_length=255)),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Camin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('admini_camin', models.ManyToManyField(blank=True, related_name='caminuri_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Masina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('tip', models.CharField(choices=[('spalatorie', 'Mașină de spălat'), ('uscator', 'Uscător')], max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('camin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.camin')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numar_camera', models.CharField(blank=True, max_length=10, null=True)),
                ('suspendat_pana_la', models.DateField(blank=True, null=True)),
                ('camin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.camin')),
                ('utilizator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramMasina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ora_start', models.TimeField()),
                ('ora_end', models.TimeField()),
                ('masina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.masina')),
            ],
        ),
        migrations.CreateModel(
            name='Rezervare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rezervare', models.DateField()),
                ('ora_start', models.TimeField()),
                ('ora_end', models.TimeField()),
                ('prioritara', models.BooleanField(default=True)),
                ('anulata', models.BooleanField(default=False)),
                ('avertisment_dat', models.BooleanField(default=False)),
                ('masina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.masina')),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
