# Generated by Django 5.2.1 on 2025-06-10 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Avertisment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('motiv', models.TextField(default='Rezervare neutilizată')),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminCamin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('camin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admini', to='booking.camin')),
            ],
        ),
        migrations.CreateModel(
            name='Masina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('camin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.camin')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('nume', models.CharField(blank=True, max_length=50, null=True)),
                ('prenume', models.CharField(blank=True, max_length=50, null=True)),
                ('numar_camera', models.CharField(blank=True, max_length=10, null=True)),
                ('suspendat_pana_la', models.DateField(blank=True, null=True)),
                ('camin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.camin')),
                ('utilizator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramMasina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ora_start', models.TimeField()),
                ('ora_end', models.TimeField()),
                ('masina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.masina')),
            ],
        ),
        migrations.CreateModel(
            name='Rezervare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rezervare', models.DateField()),
                ('ora_start', models.TimeField()),
                ('ora_end', models.TimeField()),
                ('prioritara', models.BooleanField(default=True)),
                ('anulata', models.BooleanField(default=False)),
                ('avertisment_dat', models.BooleanField(default=False)),
                ('masina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.masina')),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Uscator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('camin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.camin')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramUscator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ora_start', models.TimeField()),
                ('ora_end', models.TimeField()),
                ('uscator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.uscator')),
            ],
        ),
    ]
