# Generated by Django 5.2.1 on 2025-06-11 03:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rezervare',
            options={'ordering': ['data_rezervare', 'ora_start']},
        ),
        migrations.RemoveField(
            model_name='rezervare',
            name='avertisment_dat',
        ),
        migrations.RemoveField(
            model_name='rezervare',
            name='prioritara',
        ),
        migrations.AddField(
            model_name='rezervare',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rezervare',
            name='nivel_prioritate',
            field=models.IntegerField(choices=[(1, 'Maximă'), (2, 'Înaltă'), (3, 'Medie'), (4, 'Scăzută')], default=1),
        ),
    ]
