# Generated by Django 5.1.6 on 2025-04-28 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_admincamin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admincamin',
            name='student',
        ),
        migrations.RemoveField(
            model_name='camin',
            name='admini_camin',
        ),
        migrations.AddField(
            model_name='admincamin',
            name='email',
            field=models.EmailField(default='elena.marcu2@student.tuiasi.ro', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admincamin',
            name='camin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admini', to='booking.camin'),
        ),
        migrations.AlterField(
            model_name='camin',
            name='nume',
            field=models.CharField(max_length=50),
        ),
    ]
