# Generated by Django 5.2.1 on 2025-06-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_rezervare_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervare',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
