# Generated by Django 5.2.1 on 2025-09-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_rezervare_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilstudent',
            name='telefon',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
