# Generated by Django 5.1.6 on 2025-04-29 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_admincamin_student_remove_camin_admini_camin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masina',
            name='tip',
        ),
        migrations.CreateModel(
            name='Uscator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('camin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.camin')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramUscator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ora_start', models.TimeField()),
                ('ora_end', models.TimeField()),
                ('uscator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.uscator')),
            ],
        ),
    ]
