# Generated by Django 5.2.1 on 2025-10-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_profilstudent_telefon'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincamin',
            name='telefon',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
