# Generated by Django 5.1.6 on 2025-04-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_masina_tip_uscator_programuscator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avertisment',
            name='data_avertisment',
        ),
        migrations.AddField(
            model_name='avertisment',
            name='data',
            field=models.DateField(auto_now_add=True, default='2025-04-30'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avertisment',
            name='motiv',
            field=models.TextField(default='Rezervare neutilizată'),
        ),
    ]
