# Generated by Django 5.2.1 on 2025-10-06 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_admincamin_telefon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(max_length=20)),
                ('mesaj', models.TextField()),
                ('twilio_sid', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='queued', max_length=50)),
                ('data_trimitere', models.DateTimeField(auto_now_add=True)),
                ('data_actualizare', models.DateTimeField(auto_now=True)),
                ('utilizator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
