# Generated by Django 5.2.1 on 2025-10-10 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_smslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervalDezactivare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ora_start', models.TimeField()),
                ('ora_end', models.TimeField()),
                ('masina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervale_dezactivate', to='booking.masina')),
            ],
        ),
        migrations.DeleteModel(
            name='SMSLog',
        ),
    ]
