# Generated by Django 5.2.1 on 2025-10-13 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_intervaldezactivare_delete_smslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincamin',
            name='is_super_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admincamin',
            name='camin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.camin'),
        ),
        migrations.AlterField(
            model_name='admincamin',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='admincamin',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
