# Generated by Django 5.2.1 on 2025-10-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_admincamin_is_super_admin_alter_admincamin_camin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilstudent',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
