# Generated by Django 5.2.1 on 2025-11-10 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_profilstudent_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincamin',
            name='camin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.camin'),
        ),
    ]
