# Generated by Django 5.2.1 on 2025-11-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_admincamin_camin'),
    ]

    operations = [
        migrations.AddField(
            model_name='camin',
            name='durata_interval',
            field=models.PositiveIntegerField(default=2, help_text='Durata fiecărui interval de rezervare (ore)'),
        ),
        migrations.AlterField(
            model_name='camin',
            name='nume',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
