# Generated by Django 5.2.1 on 2026-09-30 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_notificare'),
    ]

    operations = [
        migrations.CreateModel(
            name='CerereCont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nume', models.CharField(max_length=50)),
                ('prenume', models.CharField(max_length=50)),
                ('numar_camera', models.CharField(blank=True, max_length=10)),
                ('telefon', models.CharField(blank=True, max_length=15)),
                ('stare', models.CharField(choices=[('in_asteptare', 'În așteptare'), ('aprobata', 'Aprobată'), ('respinsa', 'Respinsă')], default='in_asteptare', max_length=16)),
                ('creat_la', models.DateTimeField(auto_now_add=True)),
                ('procesat_la', models.DateTimeField(blank=True, null=True)),
                ('procesat_de', models.CharField(blank=True, max_length=254)),
                ('motiv', models.TextField(blank=True)),
                ('camin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cereri_cont', to='booking.camin')),
            ],
            options={
                'ordering': ['-creat_la', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('stare', 'in_asteptare')), fields=('email',), name='o_singura_cerere_in_asteptare')],
            },
        ),
    ]
