# Generated by Django 5.2.1 on 2026-09-30 05:08

from django.db import migrations, models


def ascunde_caminul_de_test(apps, schema_editor):
    """Căminul folosit de testele de API nu e un loc unde stă cineva."""
    apps.get_model("booking", "Camin").objects.filter(
        nume="API_TEST"
    ).update(accepta_cereri=False)


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_cererecont'),
    ]

    operations = [
        migrations.AddField(
            model_name='camin',
            name='accepta_cereri',
            field=models.BooleanField(default=True, help_text='Apare în lista de cămine din formularul de cerere de cont'),
        ),
        migrations.RunPython(
            ascunde_caminul_de_test, migrations.RunPython.noop
        ),
    ]
