# Generated by Django 5.2.1 on 2026-10-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_camin_accepta_cereri'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincamin',
            name='nume',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admincamin',
            name='primeste_notificari',
            field=models.BooleanField(default=True, help_text='Primește WhatsApp când un student cere cont în acest cămin'),
        ),
    ]
